Feat/dssc 860pvd0b4
jgnacadja/PathCollect pull request #14
Opened 2023-02-14 08:30 UTC by aertyuiop12345

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-02-16 21:20 UTC, jgnacadja requested changes

2023-02-16 21:20 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
> +        countSelectedItem = findViewById(R.id.count_selected_form);
y a t-il un besoin de compter les formulaires sur cette pages ?

2023-02-16 21:20 UTC, jgnacadja commented on strings/src/main/res/values/untranslated.xml
> +    <string name="subtitle" translatable="false">SONDAGE</string>
ce n'est pas plutôt `enquête`  ?

2023-02-17 07:58 UTC, aertyuiop12345 commented on collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
> +        countSelectedItem = findViewById(R.id.count_selected_form);
oui c'est se qui est fait sur la maquette

2023-02-17 07:59 UTC, aertyuiop12345 commented on strings/src/main/res/values/untranslated.xml
> +    <string name="subtitle" translatable="false">SONDAGE</string>
Non c'est Sondage

2023-02-22 13:55 UTC, jgnacadja approved these changes

2023-02-22 13:55 UTC, merged