feat: [DSSC#8669fx4qc] Integration de la page envoyer un formulaire finaliser
jgnacadja/PathCollect pull request #17
Opened 2023-02-15 08:31 UTC by aertyuiop12345

…inaliser

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-02-16 21:11 UTC, jgnacadja requested changes

2023-02-16 21:11 UTC, jgnacadja commented on collect_app/src/main/res/values/colors.xml
> +    <color name="surfaceButtonColor">#753081</color>
Utiliser  une couleur de la palette graphique. si elle n'existe pas vous pouvez la définir

2023-02-16 21:11 UTC, jgnacadja commented on strings/src/main/res/values/untranslated.xml
> +    <string name="form_selected" translatable="false">%s Formualaire(s) sélectionné(s)</string>
`Formulaire`

2023-02-22 17:24 UTC, aertyuiop12345 commented on collect_app/src/main/res/values/colors.xml
> +    <color name="surfaceButtonColor">#753081</color>
C'est fait

2023-02-22 17:24 UTC, aertyuiop12345 commented on strings/src/main/res/values/untranslated.xml
> +    <string name="form_selected" translatable="false">%s Formualaire(s) sélectionné(s)</string>
C'est fait

2023-02-24 14:44 UTC, Baom92 approved these changes

2023-02-27 17:48 UTC, jgnacadja requested changes

2023-02-27 17:48 UTC, jgnacadja commented on strings/src/main/res/values/untranslated.xml
> +    <string name="form_selected" translatable="false">%s Formualaire sélectionné(s)</string>
la revue précédante ne faisait pas allusion au pluriel. Mais bien a la typo : c'est `forMUlaire` et non `formUAlaire`

2023-02-27 17:48 UTC, jgnacadja commented on strings/src/main/res/values/untranslated.xml
> +    <string name="form_selected" translatable="false">%s Formualaire sélectionné(s)</string>
et merci de remettre la `(s)`

2023-02-27 18:35 UTC, jgnacadja requested changes

2023-02-27 18:35 UTC, jgnacadja commented on strings/src/main/res/values/untranslated.xml
> +    <string name="form_selected" translatable="false">%s Formulaire sélectionné(s)</string>
et  j'ai dis aussi de ne pas omettre le `(s)`. 

Autrement dit c'est `Formulaire(s)`

2023-02-28 14:07 UTC, jgnacadja approved these changes

2023-03-15 15:20 UTC, closed without merging