Update app bar & Intialize kobo account on app first launch
jgnacadja/PathCollect pull request #18
Opened 2023-02-16 15:13 UTC by Baom92

…ceuil & Configuration automatique d'un compte utilisateur à l'installation de l'application

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-02-16 21:00 UTC, jgnacadja requested changes
Il serait intéressant d'avoir le ticket lié.

2023-02-16 21:00 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/activities/AppListActivity.java
> +        toolbar.setNavigationOnClickListener(new View.OnClickListener() {
Pourquoi un clique sur toute la toolBar  ? le commentaire parle de l'icône

2023-02-16 21:00 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/activities/DeleteSavedFormActivity.kt
> +        val toolbar = this.findViewById<Toolbar>(R.id.toolbar)
verifier le besoin de la toolBar

2023-02-16 21:00 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/activities/DeleteSavedFormActivity.kt
> +            // This code will be executed when the navigation icon is clicked
On dirait du code copier-coller à tous les niveaux. ..

2023-02-16 21:00 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/activities/FirstLaunchActivity.kt
> +                "http://kc.kobo.dev.rintio.com",
Best practice : definir le fichier JSON applicatif et charger le json dans la fonction `.getAppConfigurationAsJsonWithServerDetails`

Bon ne pas oublier que les paramètres  dépendent des environnements. du coup utiliser les variables d'env.

2023-02-16 21:00 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/activities/FirstLaunchActivity.kt
> -            configureViaQrButton.setOnClickListener {
Pourquoi retirer ? en cas d'echec de chargement des variables d'env on en aura besoin

2023-02-16 21:00 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +                Intent intent = new Intent(getApplicationContext(), MainMenuActivity.class);
!!!!!!!

2023-02-16 21:00 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
> +        toolbar.setNavigationOnClickListener(new View.OnClickListener() {
Même remarque que précédemment

2023-02-16 21:00 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/activities/WebViewActivity.java
> +            @Override
Même remarque que précédemment

2023-02-16 21:00 UTC, jgnacadja commented on collect_app/src/main/res/menu/top_bar_menu.xml
> +        android:id="@+id/action_item_periodical"
Justement .
C'est justement ces  android:id  qui  devraient être appelés

2023-02-16 21:00 UTC, jgnacadja commented on strings/src/main/res/values-fr/strings.xml
> +  <string name="periodical_app">Suivi de Cycles Menstruelles</string>
Trop long. 
proposition `Mon cycle`

2023-02-16 21:00 UTC, jgnacadja commented on strings/src/main/res/values/untranslated.xml
> +    <string name="dssc_username" translatable="false">http://kc.kobo.dev.rintio.com</string>
Si la config est ici pourquoi l'écrire directement dans `FisrtLunchActivity` ??

2023-02-17 07:47 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/AppListActivity.java
> +        toolbar.setNavigationOnClickListener(new View.OnClickListener() {
Cette fonction est juste liée à l'icône de navigation et non à toute la bar

2023-02-17 09:16 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/FirstLaunchActivity.kt
> +                "http://kc.kobo.dev.rintio.com",
C'est un oublie. Je l'ai intégrer

2023-02-17 09:18 UTC, Baom92 commented on collect_app/src/main/res/menu/top_bar_menu.xml
> +        android:id="@+id/action_item_periodical"
Ils ont été utilisé mais uniquement dans le main activity vu que ces menus là n'apparaissent que sur la page d'accueil

2023-02-17 10:31 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/DeleteSavedFormActivity.kt
> +        val toolbar = this.findViewById<Toolbar>(R.id.toolbar)
La toolbar est présente sur toute les pages principales. Chacune l'initalise à son niveau puis y ajoute les menus à utiliser

2023-02-22 14:37 UTC, jgnacadja approved these changes

2023-02-22 14:49 UTC, jgnacadja requested changes
certains points n'ont pas été corrigé. au besoin demander un point live

2023-02-28 14:21 UTC, jgnacadja approved these changes

2023-03-21 14:15 UTC, Baom92 commented on strings/src/main/res/values/untranslated.xml
> +    <string name="periodical_app_package_name" translatable="false">de.arnowelzel.android.periodical</string>
Ne fais pas partie du scope du ticket

2023-04-17 08:12 UTC, jgnacadja requested changes

2023-04-17 08:12 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
> +        if (item.getItemId() == R.id.action_item_about) {
2 conditions + un default demande un switch case statement en algorithme

2023-04-17 08:12 UTC, jgnacadja commented on strings/src/main/res/values/untranslated.xml
> +    <string name="dssc_password" translatable="false">molympio</string>
Les credentials devraient être pas être des variables d'environnement ?

2023-04-18 05:25 UTC, jgnacadja approved these changes

2023-04-18 05:29 UTC, merged