feat:[DSSC-8669hujnw]Intégration de la page Apropos
jgnacadja/PathCollect pull request #19
Opened 2023-02-16 16:53 UTC by Ariellenout

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-02-16 20:34 UTC, jgnacadja requested changes

2023-02-16 20:34 UTC, jgnacadja commented on strings/src/main/res/values-fr/strings.xml
> +  <string name="tell_your_friends">Partager DSSC COLLECT</string>
@Baom92  la fonction de partage est demandée ? quelle lien est partagé quand vous cliquez sur cette action ?

2023-02-16 20:34 UTC, jgnacadja commented on strings/src/main/res/values-fr/strings.xml
> +  <string name="odk_website">Visiter le site web de DSSC COLLECT</string>
Cette fonction est elle demandée dans la cahier de charge ? si oui quelle site web est indexée ?

2023-02-16 20:34 UTC, jgnacadja commented on strings/src/main/res/values-fr/strings.xml
>    <string name="odk_forum_summary">Join the forum to get support and connect with other users!</string>
Version française ?

2023-02-16 21:03 UTC, jgnacadja requested changes
A revoir

2023-02-17 07:52 UTC, Baom92 commented on strings/src/main/res/values-fr/strings.xml
> +  <string name="odk_website">Visiter le site web de DSSC COLLECT</string>
Non elle n'a pas été demandé. Mais on a jugée nécessaire de l'ajouter. Le site web qui sera indexé sera celui du RAME. Ce click redirigera vers un article qui présente le projet

2023-02-17 07:55 UTC, Baom92 commented on strings/src/main/res/values-fr/strings.xml
> +  <string name="tell_your_friends">Partager DSSC COLLECT</string>
Elle n'est pas dans le cahier de charge. On a voulue l'ajouter pour partager le lien playstore de l'application

2023-02-17 13:32 UTC, jgnacadja requested changes

2023-02-17 13:32 UTC, jgnacadja commented on strings/src/main/res/values-fr/strings.xml
> +  <string name="odk_website">Visiter le site web de DSSC COLLECT</string>
Configure du coup le lien maintenant ou retirer ces modifs pour modifications plus tard. le mentionner dans le backlog. Donc deux solutions

2023-02-22 14:05 UTC, Baom92 requested changes

2023-02-22 14:05 UTC, Baom92 commented on strings/src/main/res/values/strings.xml
> +    <string name="FAQ_msg">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Changer le texte

2023-02-22 14:56 UTC, jgnacadja approved these changes

2023-02-27 15:43 UTC, Baom92 approved these changes

2023-02-27 17:42 UTC, jgnacadja approved these changes

2023-02-27 17:45 UTC, jgnacadja approved these changes

2023-02-27 17:45 UTC, merged