feat: [DSSC#860pvd0tr] Correction des images et taille pour la page d…
jgnacadja/PathCollect pull request #21
Opened 2023-02-20 18:06 UTC by aertyuiop12345

…'accueil

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-02-22 14:01 UTC, Baom92 requested changes

2023-02-22 14:01 UTC, Baom92 commented on collect_app/src/main/res/layout/main_menu.xml
> +                        android:textSize="17sp"
Garder une taille de texte uniforme

2023-02-22 14:01 UTC, Baom92 commented on collect_app/src/main/res/layout/main_menu.xml
> +                android:textSize="@dimen/margin_large"
La dimension est pour les marges. Créer une dimension pour la taille des textes

2023-02-22 14:01 UTC, Baom92 commented on collect_app/src/main/res/layout/main_menu.xml
> +                        app:iconSize="30dp"
Créer une dimension pour la taille des icônes au lieu de le mettre litéralement

2023-02-23 08:33 UTC, Baom92 requested changes

2023-02-23 08:33 UTC, Baom92 commented on collect_app/src/main/res/layout/main_menu.xml
> +<<<<<<< HEAD
Conflits. A corriger

2023-02-24 14:40 UTC, Baom92 approved these changes

2023-02-27 17:39 UTC, jgnacadja approved these changes

2023-02-28 13:52 UTC, merged