feat: [DSSC#8669jr6x4] Integration de la page Landing Page
jgnacadja/PathCollect pull request #22
Opened 2023-02-21 16:01 UTC by aertyuiop12345

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-02-22 13:57 UTC, Baom92 requested changes

2023-02-22 13:57 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/LandingPageActivity.java
> +    private MainMenuViewModel mainMenuViewModel;
Innutilisé. A supprimer

2023-02-22 13:57 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/LandingPageActivity.java
> +    MainMenuViewModel.Factory viewModelFactory;
Inutilisé. A supprimer

2023-02-22 13:57 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/LandingPageActivity.java
> +        getMenuInflater().inflate(R.menu.main_menu, menu);
Le menu utilisé sur cette page n'est pas celui-ci. A corriger !

2023-02-22 13:57 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/LandingPageActivity.java
> +    private CurrentProjectViewModel currentProjectViewModel;
A supprimer

2023-02-23 08:55 UTC, Baom92 commented
Il y a toujours des variables inutilisées dans le code. Android Studio les marques. Juste suivre les recommendations d'Android studio

2023-02-24 14:15 UTC, Baom92 requested changes

2023-02-24 14:15 UTC, Baom92 commented on collect_app/src/main/res/layout/landing_page.xml
> +<!--            <androidx.fragment.app.FragmentContainerView-->
Supprimer les codes comentés

2023-02-27 15:42 UTC, Baom92 approved these changes

2023-02-27 17:32 UTC, jgnacadja approved these changes

2023-02-27 17:32 UTC, merged