feat:[DSSC-8669fx4qg]Intégration de la page supprimé un formulaire en…
jgnacadja/PathCollect pull request #24
Opened 2023-02-24 10:21 UTC by Ariellenout

…voyé

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-02-24 14:13 UTC, Baom92 requested changes

2023-02-24 14:13 UTC, Baom92 commented on collect_app/src/main/res/layout/file_manager_list.xml
> +        android:layout_width="match_parent"
A supprimer puisque pas mis à jour dans le code java

2023-02-24 14:58 UTC, Baom92 approved these changes

2023-02-27 15:22 UTC, jgnacadja approved these changes

2023-02-27 15:22 UTC, merged