feat: [DSSC#8669pw2yp] Bugs page sondage
jgnacadja/PathCollect pull request #29
Opened 2023-03-15 08:59 UTC by aertyuiop12345

Closes #

#### What has been done to verify that this works as intended?
Aucun test unitaires n'a été fait sur les nouvelles insertions de code
#### Why is this the best possible solution? Were any other approaches considered?
Non
#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Aucun risque de regression. Les fonctionnalités impactés par ce travail concerne uniquement les boutons et la mise a jour des couleurs.
#### Do we need any specific form for testing your changes? If so, please attach one.
Aucun
#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
Non
#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-03-16 22:49 UTC, Baom92 approved these changes

2023-03-21 21:46 UTC, jgnacadja requested changes
A modifier

2023-03-21 21:46 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
> +        if (item.getItemId() == R.id.action_item_about) {
utiliser un switch case statement

2023-03-21 21:46 UTC, jgnacadja commented
Des conflits sur la branche

2023-03-22 09:02 UTC, Baom92 approved these changes

2023-03-31 10:43 UTC, jgnacadja approved these changes

2023-03-31 10:43 UTC, merged