feat: [DSSC#8669qnub8] Bugs Envoyer un formulaire finaliser
jgnacadja/PathCollect pull request #32
Opened 2023-03-15 13:15 UTC by aertyuiop12345

Closes #

#### What has been done to verify that this works as intended?
Aucun test unitaires n'a été fait sur les nouvelles insertions de code
#### Why is this the best possible solution? Were any other approaches considered?
Non
#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Aucun risque de regression. Les fonctionnalités impactés par ce travail concerne uniquement les boutons et la mise a jour des couleurs.
#### Do we need any specific form for testing your changes? If so, please attach one.
Aucun
#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
Non
#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [*] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-03-17 09:20 UTC, Baom92 requested changes
Le ticket a été mis à jour
Prière se référer à çà

2023-03-17 09:20 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderListActivity.java
> +            //toggleButtonLabel(findViewById(R.id.toggle_button), listView);
SUpprimer les codes commentés

2023-03-20 09:26 UTC, Baom92 approved these changes

2023-03-21 21:53 UTC, jgnacadja commented on strings/src/main/res/values/untranslated.xml
> +    <string name="upload_answer" translatable="false">Envoie du Formulaire</string>
l'envoie du formulaire n'était pas une fonction native ?

2023-03-21 21:53 UTC, jgnacadja reviewed
Need infos

2023-03-22 08:42 UTC, Baom92 commented on strings/src/main/res/values/untranslated.xml
> +    <string name="upload_answer" translatable="false">Envoie du Formulaire</string>
C'est une fonction native. Il fallait adapter la page à la maquette. Et, pendant les tests, on a remarqué que le message affiché à l'envoi du formulaire n'est pas correcte en français

2023-03-31 10:39 UTC, jgnacadja approved these changes

2023-03-31 15:08 UTC, Baom92 approved these changes

2023-04-17 08:15 UTC, jgnacadja approved these changes

2023-04-17 08:15 UTC, merged