Feat/dssc 8669mmkha
jgnacadja/PathCollect pull request #35
Opened 2023-03-17 17:50 UTC by Ariellenout

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-03-20 10:29 UTC, Baom92 requested changes

2023-03-20 10:29 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/ArticleListActivity.java
> +                .baseUrl("https://dssc-cms.000webhostapp.com/wp-json/wp/v2/")
Mettre ce lien dans le fichier untranslated et l'appeller ici

2023-03-20 10:29 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/ArticleListActivity.java
> +                    Timber.tag("Articles").i(String.valueOf(articles.size()));
Supprimer ce log

2023-03-20 10:29 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/ArticleListActivity.java
> +
Suppimer les espaces inutiles

2023-03-20 10:29 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/adapters/ArticleListAdapter.java
> +        Timber.tag("ArticleListAdapter").i(new Gson().toJson(article));
Supprimer ce log

2023-03-22 09:11 UTC, Baom92 requested changes

2023-03-22 09:11 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/LandingPageActivity.java
>                  i.putExtra(ApplicationConstants.BundleKeys.FORM_MODE,
Pas besoin de putExtra. C'est fait pour envoyer des paramètres à l'activité. Mais, ArticleListActivity ne prend aucun paramètres

2023-03-22 09:11 UTC, Baom92 commented on collect_app/src/main/res/values/strings.xml
> +<resources></resources>
Pourquoi une ressource vide ?

2023-03-22 09:11 UTC, Baom92 commented on strings/src/main/res/values/untranslated.xml
> +    <string name="api_url" translatable="false">https://dssc-cms.000webhostapp.com/wp-json/wp/v2/ </string>
Pourquoi cet espase à la fin ?

2023-03-22 09:11 UTC, Baom92 commented on strings/src/main/res/values/untranslated.xml
>      <string name="app_url" translatable="false">https://www.rame-int.org/ </string>
Pourquoi cet espace à la fin ?

2023-03-22 14:09 UTC, Baom92 approved these changes

2023-03-26 21:16 UTC, Baom92 requested changes
Eviter les modifications inutiles. Cette PR en contient trop. A corriger

2023-03-30 07:55 UTC, Baom92 approved these changes

2023-03-31 10:30 UTC, jgnacadja requested changes
Modélisation  relationel  Post, Media , à revoir

2023-03-31 10:30 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/adapters/model/Article.java
> +    public Article() {
Quel est le besoin ?

2023-04-17 10:12 UTC, Baom92 requested changes

2023-04-17 10:12 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/dao/WpApiService.java
Ce fichier n'est plus utiliser

2023-04-17 10:12 UTC, Baom92 commented on strings/src/main/res/values/untranslated.xml
> +    <string name="api_url" translatable="false">https://dssc-cms.000webhostapp.com/wp-json/wp/v2/</string>
N'est plus utilisé

2023-04-17 12:00 UTC, Baom92 approved these changes

2023-04-18 05:40 UTC, jgnacadja requested changes

2023-04-18 05:40 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/adapters/model/Post.java
> +    public Post() {
????

2023-04-18 08:24 UTC, aertyuiop12345 commented on collect_app/src/main/java/org/odk/collect/android/adapters/model/Post.java
> +    public Post() {
Le constructeur vide Post est obligatoire en Java pour  permettre la création d'objets "Post" sans donner de valeurs initiales aux champs

2023-04-24 15:02 UTC, jgnacadja approved these changes

2023-04-24 15:03 UTC, merged