feat:[DSSC-8669mcdrw] Integration des Notifications
jgnacadja/PathCollect pull request #36
Opened 2023-03-29 18:09 UTC by aertyuiop12345

Closes #

#### What has been done to verify that this works as intended?
Aucun test unitaires n'a été fait sur les nouvelles insertions de code
#### Why is this the best possible solution? Were any other approaches considered?
non
#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Aucun risque de regression. Les fonctionnalités impactés par ce travail concerne uniquement les boutons et la mise a jour des couleurs
#### Do we need any specific form for testing your changes? If so, please attach one.
aucun
#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
non
#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-03-30 14:13 UTC, Baom92 approved these changes

2023-03-31 10:01 UTC, jgnacadja requested changes
reverifier la logique de souscription au service de notification

2023-05-17 06:33 UTC, Baom92 requested changes

2023-05-17 06:33 UTC, Baom92 commented on collect_app/src/main/AndroidManifest.xml
> +    </queries>
Cette modification sert à quoi ?

2023-05-17 06:33 UTC, Baom92 commented on collect_app/src/main/AndroidManifest.xml
> +        <receiver
Celà sert à quoi ?

2023-05-17 06:33 UTC, Baom92 commented on collect_app/src/main/AndroidManifest.xml
Pourquoi toutes ces modifications dans ce fichier ?

2023-05-17 06:33 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/UninstallReceiver.java
Il sert à quoi ?

2023-05-17 06:33 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/FirstLaunchActivity.kt
> +    private fun subscribeToWP() {
La souscription sera effectué chaque fois. C'est pas logique

2023-05-17 06:33 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/LandingPageActivity.java
> +>>>>>>> e4028c08f (feat: [DSSC#8669mcdrw])
????

2023-05-21 21:05 UTC, Baom92 commented
Réponds à mes questions stp.
Et ne résout pas mes conversations

2023-05-23 04:33 UTC, Baom92 approved these changes

2023-05-25 09:00 UTC, merged