feat:[DSSC-8669xdjgx ] Integration des centres hospitaliers
jgnacadja/PathCollect pull request #37
Opened 2023-03-31 16:47 UTC by Ariellenout

Closes #

#### What has been done to verify that this works as intended?
Aucun test unitaires n'a été fait sur les nouvelles insertions de code
#### Why is this the best possible solution? Were any other approaches considered?
non
#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Aucun risque de regression.
#### Do we need any specific form for testing your changes? If so, please attach one.
aucun
#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
non
#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-04-13 08:44 UTC, Baom92 requested changes

2023-04-13 08:44 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/FirstLaunchActivity.kt
> +        AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO)
N'est pas dans le scope du ticket. Pas à modifier

2023-04-13 08:44 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/HospitalActivity.java
> +        setTitle(getString(R.string.collect_app_name));
Mettre le nom de l'hopital comme titre

2023-04-13 08:44 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/LandingPageActivity.java
> +        AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);
Ces modifications ne font pas partie du scope du projet

2023-04-13 08:44 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
> +        AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);
Ne fais pas partie du scope du ticket

2023-04-13 08:44 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/adapters/HospitalListAdapter.java
> +        import androidx.recyclerview.widget.RecyclerView;
Reformater le code de cette classe

2023-04-13 08:44 UTC, Baom92 commented on collect_app/src/main/res/layout/hospital_item_layout.xml
> +        android:layout_width="92dp"
Doit être paramétriser

2023-04-13 08:44 UTC, Baom92 commented on collect_app/src/main/res/layout/hospital_item_layout.xml
> +            android:textSize="20sp"
Utiliser les tailles définies dans dimens

2023-04-13 08:44 UTC, Baom92 commented on collect_app/src/main/res/layout/hospital_layout.xml
> +<!--    <include layout="@layout/app_bar_with_progress_bar_layout"/>-->
Pourquoi est-il commenté ?

2023-04-13 08:44 UTC, Baom92 commented on strings/src/main/res/values/untranslated.xml
> +<!--    <string name="api_gateway_url" translatable="false">http://localhost:32490/</string>-->
A supprimer

2023-04-17 10:21 UTC, Baom92 requested changes

2023-04-17 10:21 UTC, Baom92 commented on collect_app/google-services.json
> +          "package_name": "org.dssc.collect.android"
Cette modification n'est pas nécessaire et n'a aucun sens

2023-04-17 10:21 UTC, Baom92 commented on collect_app/src/debug/google-services.json
> +          "package_name": "org.dssc.collect.android"
idem

2023-04-17 10:21 UTC, Baom92 commented on collect_app/src/main/AndroidManifest.xml
> +            android:authorities="org.dssc.collect.android.provider.odk.forms"
idem

2023-04-17 10:21 UTC, Baom92 commented on collect_app/src/main/AndroidManifest.xml
> +            android:authorities="org.dssc.collect.android.provider.odk.instances"
idem

2023-04-17 10:21 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/FirstLaunchActivity.kt
> +import androidx.appcompat.app.AppCompatDelegate
Inutiliser. A supprimer

2023-04-17 10:21 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/HospitalActivity.java
> +public class HospitalActivity extends AppCompatActivity {
Elle doit extend CollectAbstractActivity

2023-04-17 10:21 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/HospitalListActivity.java
> +public class HospitalListActivity extends AppCompatActivity implements
Elle doit extend CollectAbstractActivity

2023-04-17 10:21 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/external/FormsContract.java
> +    static final String AUTHORITY = "org.dssc.collect.android.provider.odk.forms";
Mise à jour inutile

2023-04-17 10:21 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/external/InstancesContract.java
> +    public static final String AUTHORITY = "org.dssc.collect.android.provider.odk.instances";
Mise à jour inutile

2023-04-17 10:21 UTC, Baom92 commented on collect_app/src/main/res/layout/hospital_layout.xml
> +        android:layout_height="2dp"
Utiliser une variable dimen

2023-04-17 10:21 UTC, Baom92 commented on collect_app/src/main/res/layout/hospital_layout.xml
> +            android:textSize="24sp"
Utiliser une variable dimen

2023-04-17 10:21 UTC, Baom92 commented on collect_app/src/main/res/layout/hospital_list_layout.xml
> +        android:textSize="24sp"
Utiliser une variable dimen

2023-04-17 10:21 UTC, Baom92 commented on collect_app/src/main/res/layout/product_item_layout.xml
> +        android:layout_width="92dp"
idem

2023-04-17 10:21 UTC, Baom92 commented on collect_app/src/main/res/layout/product_item_layout.xml
> +                android:textSize="20sp"
idem

2023-04-17 10:21 UTC, Baom92 commented on collect_app/src/main/res/layout/product_item_layout.xml
> +                android:layout_width="20dp"
idem

2023-04-17 10:21 UTC, Baom92 commented on collect_app/src/release/google-services.json
> +          "package_name": "org.dssc.collect.android"
Modification inutile

2023-04-17 13:44 UTC, Baom92 approved these changes

2023-04-18 05:52 UTC, jgnacadja requested changes

2023-04-18 05:52 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/adapters/model/Hospital.java
> +        public Prestation() {
????

2023-04-18 05:52 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/adapters/model/Hospital.java
> +    public Hospital() {
????

2023-04-18 08:33 UTC, aertyuiop12345 commented on collect_app/src/main/java/org/odk/collect/android/adapters/model/Hospital.java
> +        public Prestation() {
Le constructeur vide Prestation est obligatoire en Java pour permettre la création d'objets "Prestation" sans donner de valeurs initiales aux champs

2023-04-18 08:34 UTC, aertyuiop12345 commented on collect_app/src/main/java/org/odk/collect/android/adapters/model/Hospital.java
> +    public Hospital() {
Le constructeur vide Hospital est obligatoire en Java pour permettre la création d'objets "Hospital" sans donner de valeurs initiales aux champs

2023-05-02 20:12 UTC, Baom92 requested changes

2023-05-02 20:12 UTC, Baom92 commented on collect_app/build.gradle
> +        applicationId('org.koboc.collect.android')
Ne fais pas partie du scope du ticket

2023-05-02 20:12 UTC, Baom92 commented on collect_app/google-services.json
> +          "package_name": "org.koboc.collect.android"
Ne fait pas partie du scope du ticket

2023-05-02 20:12 UTC, Baom92 commented on collect_app/src/debug/google-services.json
> +          "package_name": "org.koboc.collect.android"
idem

2023-05-02 20:12 UTC, Baom92 commented on collect_app/src/main/AndroidManifest.xml
> +            android:authorities="org.koboc.collect.android.provider.odk.forms"
idem

2023-05-02 20:12 UTC, Baom92 commented on collect_app/src/main/AndroidManifest.xml
> +            android:authorities="org.koboc.collect.android.provider.odk.instances"
idem

2023-05-02 20:12 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/external/FormsContract.java
> +    static final String AUTHORITY = "org.koboc.collect.android.provider.odk.forms";
idem

2023-05-02 20:12 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/external/InstancesContract.java
> +    public static final String AUTHORITY = "org.koboc.collect.android.provider.odk.instances";
idem

2023-05-02 20:12 UTC, Baom92 commented on collect_app/src/main/res/layout/add_discussion_layout.xml
> +            android:layout_width="@dimen/size_width"
idem

2023-05-02 20:12 UTC, Baom92 commented on collect_app/src/release/google-services.json
> +          "package_name": "org.koboc.collect.android"
idem

2023-05-04 20:57 UTC, Baom92 approved these changes

2023-05-05 08:34 UTC, jgnacadja requested changes

2023-05-05 08:34 UTC, jgnacadja commented on strings/src/main/res/values-fr/strings.xml
> +  <string name="service_title">Par services</string>
ce use case est demandé ?

2023-05-05 10:34 UTC, aertyuiop12345 commented on strings/src/main/res/values-fr/strings.xml
> +  <string name="service_title">Par services</string>
Non ce use case n'est pas demandé

2023-05-11 07:57 UTC, jgnacadja approved these changes

2023-05-11 07:58 UTC, merged