feat: [DSSC#8669zgm2y] Integration des modifications
jgnacadja/PathCollect pull request #39
Opened 2023-04-11 17:42 UTC by aertyuiop12345

Closes #

#### What has been done to verify that this works as intended?
Aucun test unitaires n'a été fait sur les nouvelles insertions de code
#### Why is this the best possible solution? Were any other approaches considered?
non
#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Aucun risque de regression.
#### Do we need any specific form for testing your changes? If so, please attach one.
Aucun
#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
Non
#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-04-13 09:37 UTC, Baom92 requested changes

2023-04-13 09:37 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/LandingPageActivity.java
> +        builder.setMessage("Pour accéder à la fonctionnalité de gestion de cycle menstruel, vous serez redirigée vers l'application mobile Periodical. Si vous n’avez pas encore l’application Periodic
Mettre ces textes là dans le fichiers strings.xml

2023-04-13 09:37 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/LandingPageActivity.java
> +        builder.setPositiveButton("J’ai lu et bien", new DialogInterface.OnClickListener() {
Ce texte n'est pas correct

2023-04-13 09:37 UTC, Baom92 commented on strings/src/main/res/values/untranslated.xml
> +    <string name="get_quest" translatable="false">Télécharger un Questionnaire Vierge</string>
Pourquoi changer le libellé des boutons ? Utiliser les anciens libellés

2023-04-17 10:26 UTC, Baom92 requested changes

2023-04-17 10:26 UTC, Baom92 commented on collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
> +        getFormsButton.setText(getString(R.string.questionnaire_form));
Pourquoi changer le nom ? Garder l'ancien nom

2023-04-17 10:26 UTC, Baom92 commented on collect_app/src/main/res/layout/main_menu.xml
> +                    tools:text="@string/questionnaire_form" />
Garder l'ancien texte

2023-04-17 10:26 UTC, Baom92 commented on collect_app/src/main/res/layout/main_menu.xml
> +                    tools:text="@string/fill_quest" />
Garder l'ancien texte

2023-04-17 10:26 UTC, Baom92 commented on strings/src/main/res/values/untranslated.xml
> +    <string name="questionnaire_form" translatable="false">Télécharger un Questionnaire Vierge</string>
A supprimer. Garder l'ancien texte pour le bouton

2023-04-17 10:26 UTC, Baom92 commented on strings/src/main/res/values/untranslated.xml
> +    <string name="fill_quest" translatable="false">Remplir un Questionnaire</string>
A supprimer. Garder l'ancien texte pour le bouton

2023-04-17 12:06 UTC, Baom92 approved these changes

2023-04-18 05:53 UTC, jgnacadja approved these changes

2023-04-18 05:54 UTC, merged