feat: [DSSC#866a6dpf6] Integration de la langue par defaut de l'appli…
jgnacadja/PathCollect pull request #41
Opened 2023-05-02 08:43 UTC by aertyuiop12345

…cation en francais

Closes #

#### What has been done to verify that this works as intended?
Aucun test unitaires n'a ete fait sur les nouvelles insertions de code 
#### Why is this the best possible solution? Were any other approaches considered?
non
#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Aucun risque de regression
#### Do we need any specific form for testing your changes? If so, please attach one.
Aucun
#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
non
#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-05-02 20:32 UTC, Baom92 approved these changes

2023-05-05 08:30 UTC, jgnacadja requested changes

2023-05-05 08:30 UTC, jgnacadja commented on collect_app/src/main/java/org/odk/collect/android/activities/CollectAbstractActivity.java
> +        Configuration config = new Configuration();
A quel niveau ils avaient configuré la langue par défaut ?

2023-05-11 07:59 UTC, jgnacadja approved these changes

2023-05-11 10:48 UTC, merged