feat: [DSSC#866a6cnb9] Mise a jour de l'application de Mon Cycle
jgnacadja/PathCollect pull request #42
Opened 2023-05-02 09:19 UTC by aertyuiop12345

Closes #

#### What has been done to verify that this works as intended?
Aucun test unitaires n'a ete fait sur les nouvelles insertions de code 
#### Why is this the best possible solution? Were any other approaches considered?
non
#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Aucun risque de regression
#### Do we need any specific form for testing your changes? If so, please attach one.
Aucun
#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
Non
#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-05-02 20:34 UTC, Baom92 approved these changes

2023-05-12 12:48 UTC, jgnacadja requested changes

2023-05-12 12:48 UTC, jgnacadja commented on strings/src/main/res/values/untranslated.xml
> +>>>>>>> 30a71d20c (feat: [DSSC#866a6cnb9] Mise a jour de l'application de Mon Cycle)
pourquoi il y a des conflits git dans le code ?

2023-05-12 12:48 UTC, jgnacadja commented on strings/src/main/res/values/untranslated.xml
> +<<<<<<< HEAD
verifier les conflits git

2023-05-12 14:08 UTC, jgnacadja approved these changes

2023-05-12 14:08 UTC, merged